#!/bin/bash
proc=$(find config > /dev/null 2>&1 ; echo "$?")

if [ $proc != 0 ]
then
echo -e "\n\033[01;31m Nenhum Canal configurado!\n"
read -p " Digite o link socialblade aqui ---> " conf
matrix=$(curl $conf > /dev/null 2>&1 ; echo "$?")

   
    if [ $matrix != 0 ]
    then
    echo -e "\033[01;31m\n URL Inválida!\n"
    else
    echo "$conf" > config
    echo -e "\n\033[01;32m Salvando configurações...\n"
    sleep 3
    fi

exit
else
config=$(cat config)

curl $config > .info 2>&1 | echo -e "\n\033[01;32m Carregando Resultados...\033[m"

sleep 2

cont=$(cat .info | grep Subscribers | awk -F'>' '{print $6}' | tr '</span' ' ')

ini=$(cat .info | grep " - " | awk -F'$' '{print $2}' | tail -2 | awk '{print $1}')
fin=$(cat .info | grep " - " | awk -F'$' '{print $3}' | tail -2 | awk '{print $1}')
nome=$(cat .info | grep "YouTube Progress Graphs for" | awk -F'for' '{print $2}' | tr '</h2>' ' ')

echo -e "\n \033[01;35mNome do Canal --->\033[32m $nome\033[m"

echo -e "\n \033[01;35mNúmero atual de inscritos do Canal --->\033[32m $cont\n\033[m"

echo -e " \033[01;35mGanho por mês de --->\033[32m R$ $ini a $fin Dólares\n\033[m"

fi
